version: "3.7"
services:
  etl_clan_del_dragon:
    image: etl_clan_del_dragon
    container_name: etl_clan_del_dragon
    restart: always 
    tty: true
    ports:
      - 8300:8300
    networks:
      - app-network
    volumes:
      - ./etl/:/etl/
    depends_on:
      - mysql_clan_del_dragon
  mysql_clan_del_dragon:
    image: mysql:8.0.30-debian
    # NOTE: use of "mysql_native_password" is not recommended:
    # https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    container_name: mysql_clan_del_dragon
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: always
    networks:
      - app-network
    ports:
      - 3306:3306
    volumes:
      # All the data will be persisted at ./db/data on the host 
      - ./db/data/:/var/lib/mysql
      - ./api/scripts/:/scripts/
      # executing a first set of SQL code to initialize the database
      - ./api/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      # Password for the root user
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: clan_del_dragon
  client_clan_del_dragon:
    image: client_clan_del_dragon
    container_name: client_clan_del_dragon
    tty: true
    ports:
      - 3000:3000
    networks:
      - app-network
    volumes:
      - ./client/:/frontend/
    depends_on:
      - api_clan_del_dragon
      - etl_clan_del_dragon
    environment:
      REACT_APP_ADMINISTRATIVE_API: api_clan_del_dragon
      REACT_APP_MODEL_API: etl_clan_del_dragon
  api_clan_del_dragon:
    image: api_clan_del_dragon
    container_name: api_clan_del_dragon
    tty: true
    ports:
      - 8000:8000
    networks:
      - app-network
    volumes:
      - type: bind
        source: ./api/
        target: /backend/
    depends_on:
      - mysql_clan_del_dragon
    environment:
      API_PORT: 8000
      DB_HOST: mysql_clan_del_dragon
      DB_NAME: clan_del_dragon
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 12345678

networks:
  app-network:
    driver: bridge
