CREATE DATABASE IF NOT EXISTS `gonzalozambrano`;
USE `gonzalozambrano`;

DROP TABLE IF EXISTS producto1;
CREATE TABLE producto1(Id DOUBLE,Nombre VARCHAR(100),Precio DOUBLE,Tamanio VARCHAR(10),Stock DOUBLE);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (1,'Aceite crio',4,'1L',20);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (2,'Aceite crio',2,'1/2L',30);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (3,'Aceite crio',1.25,'300ML',30);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (4,'Aceite gira',6.5,'1L',30);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (5,'Aceite gira',3.25,'1/2L',30);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (6,'Aceite de oliva virgen ',7.3,'1L',30);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (7,'Aceite de oliva extra virg',9.6,'1L',30);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (8,'Azu la troncal ',0.5,'1/2KG',30);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (9,'Azu la troncal ',0.2,'1/4KG',30);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (10,'Azu la troncal ',0.85,'1KG',30);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (11,'Azu valdez',0.55,'1/2KG',30);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (12,'Azu valdez',0.24,'1/4KG',20);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (13,'Azu valdez',0.9,'1KG',20);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (14,'Azu san carlos ',0.45,'1/2KG',20);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (15,'Azu san carlos ',0.18,'1/4KG',20);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (16,'Azu san carlos ',0.8,'1KG',20);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (17,'Azucar more san carlos ',0.45,'1/2KG',20);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (18,'Azucar more san carlos ',0.18,'1/4KG',20);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (19,'Azucar more la troncal',0.8,'1KG',20);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (20,'Azucar more la troncal',0.5,'1/2KG',20);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (21,'Azucar more la troncal',0.2,'1/4KG',20);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (22,'Azucar more san carlos ',0.85,'1KG',20);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (23,'Azucar more valdez',0.55,'1/2KG',20);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (24,'Azucar more valdez',0.24,'1/4KG',20);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (25,'Azucar more valdez',0.9,'1KG',20);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (26,'Manteca 3 Chan',0.8,'1/2KG',20);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (27,'Manteca 3 Chan',0.4,'1/4KG',20);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (28,'Manteca 3 Chan',1.6,'1KG',20);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (29,'Cocoa la unive',1,'170G',20);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (30,'Cocoa rica',1.25,'170G',20);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (31,'Mante girasol',1.5,'1/2 LB ',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (32,'Mante girasol',3,'1 LB',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (33,'Mante bonella ',1.8,'1/2 LB',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (34,'Mante bonella ',3.6,'1 LB',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (35,'Mante regia ',2.25,'1/2 LB',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (36,'Mante regia ',4.5,'1 LB',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (37,'Lec nutri',1,'1L',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (38,'Lec nutri',0.5,'1/2L',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (39,'Lec nutri deslactosada',1.6,'1L',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (40,'Lec nutri deslactosada',0.8,'1/2L',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (41,'Lec nutri descremada',1.8,'1L',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (42,'Lec nutri descremada',0.95,'1/2L',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (43,'Lec nutrileche ',0.2,'1/4L',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (44,'Lec nutrileche ',0.8,'1L',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (45,'Lec nutrileche ',0.45,'1/2L',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (46,'Lec nutrileche deslactosada',0.35,'1/4L',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (47,'Lec nutrileche deslactosada',1.35,'1L',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (48,'Lec nutrileche deslactosada',0.65,'1/2L',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (49,'Lec nutrileche descremada',0.45,'1/4L',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (50,'Lec nutrileche descremada',1.4,'1L',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (51,'Lec nutrileche descremada',0.9,'1/2L',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (52,'Arroz enveje ',0.55,'1LB',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (53,'Arroz fresc',0.45,'1LB',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (54,'Arroz integ',0.8,'1LB',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (55,'Pas Colgate ',1.25,'50 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (56,'Pas Colgate ',2.3,'100 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (57,'Pas Colgate ',2.9,'150 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (58,'Pas polar ',1,'50 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (59,'Pas polar ',1.9,'100GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (60,'Pas polara',2.2,'150GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (61,'Cola Fant',0.35,'300 ML',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (62,'Coc cola',0.45,'300 ML',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (63,'Cola Spri',0.3,'300 ML',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (64,'Coc cola',2.6,'3 LT',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (65,'Cola Spri',2.5,'3 LT',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (66,'Big Col',0.25,'500 ML',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (67,'Big Col',0.5,'1 LT',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (68,'Cola Fior',0.35,'300 ML',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (69,'Coc cola',2.25,'2 LT',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (70,'Coc Cola',1,'1 LT',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (71,'Cola Fior',1,'1,35 LT',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (72,'Big Col',1,'1,85 LT',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (73,'Cola Pep',0.4,'355 ML',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (74,'Cola Pep',0.5,'1 LT',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (75,'Cola Pep',1,'2 LT',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (76,'V220',0.35,'330 ML',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (77,'Viv  100 Zero',1,'475 ML',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (78,'Viv 100',0.5,'300 ML',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (79,'Mons Energy',3,'473 ML',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (80,'Spora',0.5,'500 ML',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (81,'Power',1,'1 LT',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (82,'GATORA',1,'750 ML',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (83,'Pony Malt',0.25,'200 ML',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (84,'Pony Malt',0.4,'330 ML',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (85,'Pony Malt',1,'1 LT',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (86,'Pimi molida ILE',0.8,'50 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (87,'Pimi molida La Original',0.6,'50 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (88,'Ajo en pas ILE',1.9,'500 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (89,'Ajo en pas ILE',1.25,'320 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (90,'Aliño comp ILE',1.05,'320 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (91,'Sazon en pasta ILE',1.9,'500 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (92,'La Sazon Mag',1.35,'200 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (93,'La Sazon Mag',3.2,'550 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (94,'La Sazon Los And',2.8,'688 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (95,'Meg Sazon ILE',1.2,'200 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (96,'Sals de tomate Maggi',0.95,'200 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (97,'Sals de tomate Los Andes',1.1,'200 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (98,'Sals de tomate Maggi',0.6,'100 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (99,'Most Maggi',1,'200 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (100,'Most Maggi',0.65,'100 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (101,'Most Los Andes',1,'200 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (102,'Atún Isabel Lomitos en acei Giras',1.35,'160 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (103,'Atún Real Lomitos en acei Giras',1.45,'140 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (104,'Atún Vam camps  Lomitos en acei ',1.2,'142 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (105,'Atún ILE Lomitos en acei Giras',1.3,'170 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (106,'Atún Vam camps  en agu',1.69,'184 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (107,'Papel Higie triple Hoja Familia x6',2,'15 M C/U',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (108,'Papel Higie doble Hoja Elite x4',2.5,'25 M C/U',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (109,'Papel Higie cuatro hojas Familia x4',4.3,'15 M C/U',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (110,'Papel Higie triple Hoja Elite x4',3,'18 M C/U',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (111,'Det en polvo Ciclón Suavizante',3.55,'1.2 KG',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (112,'Det Líquido Ciclón doypack',1,'300 ML',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (113,'Det Líquido Ciclón doypack',2,'900 ML',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (114,'Det Ciclón Xtra Power',6.3,'2 KG',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (115,'Det Limón Ciclón',3.35,'1.2 KG',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (116,'Det Ciclón Xtra Power',2,'600 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (117,'Det Ciclón frutal',2,'600 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (118,'Det Deja en polvo primav',11.99,'5 KG',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (119,'Det Deja en polvo primav',1,'340 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (120,'Det Deja en polvo Limón',1,'340 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (121,'Det Deja en polvo Floral',1,'340 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (122,'Det Deja Liquido Doypack',1,'300 ML',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (123,'Det Deja en polvo Aloe Vera',3,'1,2 KG',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (124,'Lavav en barra Floral Deja',0.6,'250 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (125,'Lavav en barra Floral Deja',0.7,'350 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (126,'Lavav en barra Limón Deja',0.7,'350 GR',40);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (127,'Det Deja en polvo Aloe Vera',5.5,'2 KG',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (128,'Det Deja en polvo primavera',5.5,'2 KG',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (129,'Det Deja en polvo Floral',3,'1,2 KG',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (130,'Det Deja en polvo Limón',3,'2,2 KG',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (131,'Det Fab en polvo Flores',13,'5 KG',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (132,'Det Fab en polvo Limón',13,'5 KG',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (133,'Det Fab en polvo Flores',6,'2 KG',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (134,'Det Fab en polvo BLU',3.2,'1 KG',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (135,'Det Fab en polvo Limón',3.2,'1 KG',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (136,'Jab Liquido protex Avena',3,'221 ML',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (137,'Jab Protex Avena x4',4.3,'110 GR C/U',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (138,'Jab protex Limpieza Prof x4',4.6,'110 GR C/U',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (139,'Jab Protex Avena x4',2.6,'75 GR C/U',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (140,'Jab Protex Herbal x3',3.3,'110 GR C/U',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (141,'Jab Protex Avena x3',3.3,'110 GR C/U',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (142,'Jab Protex Limpieza Profunda x4',2.6,'75 GR C/U',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (143,'Jab Jolly Manzanilla x5',1.6,'75 GR C/U',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (144,'Jab Jolly clásico x4',1.7,'100 GR C/U',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (145,'Jab líquido Jolly',2.6,'500 ML',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (146,'Jab Jolly Manzanilla x6',2.6,'100 GR C/U',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (147,'Jab Jolly Manzanilla x3',1.6,'100 GR C/U',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (148,'Pan mold Mode',1.6,'550 GR',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (149,'Pan medio mold integral Mode',1.4,'350 GR',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (150,'Pan mini mold integ Dandy',0.85,'250 GR',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (151,'Pan mini mold Dandy',0.85,'250 GR',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (152,'Pan mold Dandy',1.6,'500 GR',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (153,'Pan mold Supan Integ',1.5,'500 GR',55);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (154,'Pan mold Supan',1.6,'500 GR',35);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (155,'Gall ricas',0.45,'58 GR',35);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (156,'Gall Oreo x6',0.4,'126 GR',35);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (157,'Gall Oreo x4',0.3,'36 GR',35);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (158,'Gall de coco Nestle',1.3,'206 GR',35);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (159,'Gall de coco Koki',1,'210 GR',35);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (160,'Gall María',0.85,'172 GR',35);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (161,'Tango Choco blanc',0.35,'25 GR',35);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (162,'Gall Ducales',2,'243 GR',35);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (163,'Gall Ritz x4',2,'268 GR',35);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (164,'Gall salticas ',0.45,'70 GR',35);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (165,'Gall mini Chips Ahoy',0.4,'50 GR',35);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (166,'Gall Santin Noel',2,'300 GR',35);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (167,'Gall Oreo Mini',0.5,'40 GR',35);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (168,'Gall mini Ritz',0.5,'50 GR',35);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (169,'Gall Club Social paq x9',1.95,'234 GR',35);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (170,'Gall Ducales',2.25,'360 GR',35);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (171,'Pap frit Ruffles Cebolla',1.35,'147 GR',35);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (172,'Pap frit Ruffles Natural',1.35,'147 GR',35);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (173,'Pap frit Ruffles Natural',2.4,'260 GR',35);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (174,'Pap frit Ruffles Picante',1.2,'147 GR',35);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (175,'Pap frit Sarita Cebolla',1.3,'100 GR',25);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (176,'Pap frit Ruffles Cebolla',0.5,'42 GR',25);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (177,'Pap frit Ruffles Natural',0.5,'42 GR',25);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (178,'Hari de trig YA con levadura',3,'1 KG',25);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (179,'Hari de trig Amancai con polvo de horn',1.7,'1 KG',25);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (180,'Hari de trig YA con Polvo de horn',4.7,'2 KG',25);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (181,'Hari de trig Estrella de octubre',1.6,'1 KG',25);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (182,'Hari de trig Amancai con polvo de horn',0.6,'250 GR',25);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (183,'Hari de trig YA',2.3,'1 KG',25);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (184,'Hari de trig Dona Petrona',1.6,'500 GR',25);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (185,'Aven Ya',0.6,'250 GR',25);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (186,'Aven Ya',1.55,'1000 GR',25);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (187,'Aven Quaker',1.2,'500 GR',25);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (188,'Aven Quaker',0.65,'250 GR',25);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (189,'Aven Quaker',2.2,'1 KG',25);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (190,'Servill Familia',1.8,'200 U',25);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (191,'Servill Familia',1.6,'300 U',25);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (192,'Servill Familia',0.6,'100 U',25);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (193,'Servill Familia Acolcha',1,'100 U',25);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (194,'Servill Familia Decor',1.3,'100 U',25);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (195,'Gelat toni',0.75,'200 GR',25);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (196,'Lec Chocolat toni',0.6,'200 ML',25);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (197,'Caf Lato toni Tetrabrick',0.85,'250 CC',25);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (198,'Lec toni Chocolat',3,'1 LT',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (199,'Lec toni MI pack x6 surtido',4.9,'200 ML C/U',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (200,'Lec toni sabori',0.85,'200 ML',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (201,'Lec toni tetra Brik Frutilla',0.65,'200 ML',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (202,'Gelat toni Manzana',0.75,'200 MG',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (203,'Gelat toni Cereza',0.75,'200 MG',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (204,'Gelat Chiki Toni Fresa',0.5,'120 MG',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (205,'Manj toni',1.5,'250 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (206,'Manj Dulac',1.4,'250 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (207,'Manj Arequipe',2.9,'500 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (208,'Manjar Arequipe',1.8,'250 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (209,'Sal Cris - Sal ',0.3,'500 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (210,'Sal Pacífic',0.25,'500 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (211,'Sal Cris - Sal ',0.5,'1 KG',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (212,'Sal parrill Cris - Sal',2.2,'500 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (213,'Sal Cris - Sal ',0.85,'2 KG',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (214,'Sazon a las finas Hierb Condimensa',1,'50 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (215,'Ajinomot',0.8,'100 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (216,'Pimi Molida Condimensa',1,'55 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (217,'Agu Dasani',0.6,'1,2 LT',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (218,'Agu Mineral con gas Güitig',0.6,'500 ML',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (219,'Agu All Natural',1.2,'6 LT',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (220,'Agu Dasani',0.4,'600 ML',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (221,'Agu All Natural',0.95,'2 LT',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (222,'Agu All Natural',0.5,'1 LT',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (223,'Agu Cielo',0.3,'625 ML',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (224,'Agu Mineral con gas Güitig',1,'1,5 LT',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (225,'Agu CIelo',0.5,'1.2 LT',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (226,'Agu Mineral con gas Güitig',1.65,'3 LT',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (227,'Agu Dasani',1.3,'3,8 LT',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (228,'Cerv Club premium x6',4.99,'355 ML C/U',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (229,'Cerv Corona x6',12.5,'355 ML C/U',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (230,'Cerv Club premium x6',6.3,'330 ML C/U',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (231,'Cerv Club Platino x6',6.3,'330 ML C/U',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (232,'Cerv Club premium x4',3.99,'269 ML C/U',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (233,'Cerv Pilsener Light x4',2.99,'269 ML C/U',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (234,'Cerv Biela Reserva x6',3.99,'355 ML C/U',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (235,'Cerv Club Premium Doble malta x6',6.3,'330 ML C/U',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (236,'Cerv Pilsener Light x6',6.7,'330 ML C/U',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (237,'Cerv Biela x12',10.5,'355 ML C/U',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (238,'Cerv Pilsener x4',2.99,'269 ML C/U',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (239,'Cerv Pilsener x6',6.7,'330 ML C/U',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (240,'Cerv Siembra x6',5.2,'355 ML C/U',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (241,'Cerv Amstel x12',10.5,'355 ML C/U',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (242,'Cerv Biela Light x12',10.5,'355 ML C/U',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (243,'Cerv Amstel x6',5.4,'355 ML C/U',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (244,'Cerv Stella Artois x6',7.4,'330 ML C/U',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (245,'Choc Rocklets',0.5,'35 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (246,'Choc para taza Superior',1.3,'100 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (247,'Choc en polvo Ricacao',2,'440 GR ',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (248,'Choc para reposteria Nestle',1.4,'100 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (249,'Choc para reposteria Nestle',2.5,'200 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (250,'Choc Galak',0.5,'20 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (251,'Choc Manicho',0.5,'28 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (252,'Choc Jet',0.5,'26 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (253,'Choc Nikolo',0.25,'21 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (254,'Gel par cabel Biolans',2,'200 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (255,'Gel par cabel Rolda',5,'500 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (256,'Gel par cabel Trance',3,'1 KG',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (257,'Gel par cabel Ego Power',2.8,'200 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (258,'Gel par cabel Ego Attraction',2.8,'200 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (259,'Gelatina en polvo Gel Hada',1.6,'200 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (260,'Gel para cabello Ego Attraction',5.8,'500 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (261,'Gel para cabello Ego Power',5.8,'500 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (262,'Gelat sin sabor Gel Hada',0.99,'30 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (263,'Gelat en polvo Gel Hada',2.9,'400 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (264,'Gelat Sin sabor Royal',0.3,'11 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (265,'Gelat en polvo Royal',0.7,'40 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (266,'Gelat en polvo Royal',3.25,'400 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (267,'Polv para horn Royal ',1.6,'100 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (268,'Gelat en polvo Royal',2.1,'200 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (269,'Chantilly Roy',1.6,'100 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (270,'Flan Roy',1.4,'80 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (271,'Chic Agogo',3,'345 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (272,'Chic Trident',0.5,'8,5 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (273,'Chic Trident',1.5,'30,6 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (274,'Fosf Sol x10',0.65,'',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (275,'Fosf Fogata x10',0.55,'',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (276,'Mayo Gustadina',1.3,'200 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (277,'Mayo Facundo',1.2,'200 GR',67);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (278,'Mayo Girasol',1.4,'200 GR',65);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (279,'Mayo Maggi',1.6,'200 GR',65);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (280,'Mayo Maggi',6,'900 GR',65);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (281,'Mayo Los Andes',1.5,'200 GR',65);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (282,'Mayo Gustadina',3,'400 GR',65);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (283,'Mayo Alacena',1,'200 GR',65);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (284,'Mayo Maggi',2.9,'400 GR',65);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (285,'Vin Tinto Selecto',7,'750 ML',65);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (286,'Vin Tinto Del Morro',8.3,'750 ML',65);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (287,'Vin Blanco Peñasol',7,'750 ML',65);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (288,'Vin Merlot Casillero del Diablo',23.9,'750 ML',65);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (289,'Sham Sedal',4,'340 ML',65);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (290,'Sham Johnson',4,'400 ML',65);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (291,'Sham Pantene',8,'400 ML',65);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (292,'Sham H&S Caspa',3.6,'180 ML',65);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (293,'Sham H&S ',13,'700 ML',65);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (294,'Desod Spray Axe Seco',3.6,'150 ML',45);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (295,'Desod Rexona Roll ON',3,'50 ML',45);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (296,'Desod Gillette',10,'82 GR',45);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (297,'Desod Speed Stick 24/7',7,'85 GR',45);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (298,'Desod Lady Speed Stick',2.8,'50 ML',45);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (299,'Prestob Gillette x2 ',4.6,'',45);
INSERT INTO producto1 (Id,Nombre,Precio,Tamanio,Stock) VALUES (300,'Vodka Russk',10.9,'750 ML',45);
